sudo: required
dist: trusty
language: python
python:
- '3.5'
- '3.6'
env:
  matrix:
  - DJANGO_MAX=1.11.100 DB=postgres TEST=pulp
  - DJANGO_MAX=2.2.100 DB=postgres TEST=pulp
  - TEST=docs
  global:
  - secure: UEmWZlefoDAa35ruK/eiD1awvdeaeesojWLH0gUUHklW4P9YrfN2hneNSGIS6EF36ZWYi6XN+vt4c4tuva48gB5vAOmA+hAvVPumQF0xdo6RStYasUFF+CPqWuTjQZsaqVEmA3FKF6BEbn+2d4G6qIJCSQUKoaD8M3Z4b6tzisaaFe+ehxHY4PVhCIGvzOrI41ws2mbp8Vq5A3ZN8NKefgAs74QOmHlVXBiyA5Qh/mNtN0sRf/LyL2GXEvYAkVH4euxmVaGDzyyT4S1qAPFAld0YFokln4idS1ur9c3MiC+0XXhUNht8PwysN/4VlVfZCEtddbnn3xTI4t4TLi/JCFYCBWuCUxHeqhqY0IcAc8IBVWugFkcmNe3TpzZdy6nr0IfRho+8DVqcw+pj2lWdg5xKFOPa35DasEwAWJY4LrXcMCBBfW1NIW3GAE1ry/vpVArx9LxyKHzRvTwH4jK9e4pXTylyI30LINnzCatWOJCgUEytKY27i81h9C/Ej0Z0bY3CCbbtGDZYKL5GyZPcTRQs6ZEmJaFumyU1bSGsp2bGIjy1sqvdyElPOYCLUsmkrj763oNnzuNAQ3/GnsX50jUILKGmLkwHxVjjlcleV1wm7JFPPd+EsaOLfirQZHEJn8OPdjiSOWBW+0KA/Cy6VKl9r/UFtdmHfU4PupV8SzA=
matrix:
  fast_finish: true
addons:
  postgresql: '9.5'
services:
- postgresql
- rabbitmq
install: source .travis/install.sh
before_script: source .travis/before_script.sh
script: source .travis/script.sh
stages:
- name: test
- name: deploy-pulpcore
  if: tag =~ ^pulpcore-3.0.0*
- name: deploy-plugin
  if: tag =~ ^pulpcore-plugin-3.0.0*
- name: deploy-common
  if: tag =~ ^pulpcore-common-3.0.0*
jobs:
  include:
  - stage: deploy-pulpcore
    script: skip
    deploy:
      provider: script
      script: bash .travis/deploy.sh pulpcore
      on:
        tags: true
  - stage: deploy-plugin
    script: skip
    deploy:
      provider: script
      script: bash .travis/deploy.sh plugin
      on:
        tags: true
  - stage: deploy-common
    script: skip
    deploy:
      provider: script
      script: bash .travis/deploy.sh common
      on:
        tags: true
