sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
language: python
python:
    # python versions used in el7 SCL & supported fedora
    - "3.5"
    - "3.6"
env:
  - DJANGO_MAX=1.11.100 DB=postgres TEST=pulp
  - DJANGO_MAX=2.2.100 DB=postgres TEST=pulp
  - TEST=docs
matrix:
  fast_finish: true
addons:
    # postgres versions provided by el7 RHSCL (lowest supportable version)
    postgresql: "9.5"
services:
    - postgresql
    - rabbitmq
before_script: source .travis/before_script.sh
stages:
  - name: install
  - name: test
  - name: deploy
    if: tag =~ ^3.0.0b*
jobs:
  include:
    - stage: install
      script: source .travis/install.sh
    - stage: test
      script: source .travis/script.sh
    - stage: deploy
      script: source .travis/push-pypi.sh
