sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
language: python
python:
    # python versions used in el7 SCL & supported fedora
    - "3.5"
    - "3.6"
env:
  - DJANGO_MAX=1.11.100 DB=postgres TEST=pulp
matrix:
  fast_finish: true
addons:
    # postgres versions provided by el7 RHSCL (lowest supportable version)
    postgresql: "9.5"
services:
    - postgresql
    - rabbitmq

jobs:
  include:
    - stage: install
      script: source .travis/install.sh
    - stage: before-test
      script: source .travis/before_script.sh
    - stage: test
        script: source .travis/script.sh
    - stage: deploy
      deploy:
        provider: script
        script: source .travis/deploy.sh
        on:
          branch: rtd-test
